openapi: 3.0.3
info:
    title: Tooren Romaros
    version: "0.1"
components:
    schemas:
        User:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                user_first_name:
                    type: string
                user_last_name:
                    type: string
                user_birthday:
                    type: string
                user_super_critic:
                    type: boolean
                user_about:
                    type: string
                user_email:
                    type: string
                user_password:
                    type: string
        Comment:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                creates_user_id:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belongs_film_id:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                comment_body:
                    type: string
                comment_datetime:
                    type: string
                comment_like_count:
                    type: integer
        Critic_Review:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                publish_user_id:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belongs_film_id:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                post_datetime:
                    type: string
                post_discuss_count:
                    type: integer
                post_like_count:
                    type: integer
                post_body:
                    type: string
                post_tittle:
                    type: string
        Discuss:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                publish_user_id:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belong_post_id:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                discuss_like_count:
                    type: integer
                discuss_body:
                    type: string
                discuss_tittle:
                    type: string
        Film:
            allOf:
                - type: object
                  properties:
                        uuid:
                            type: string
                            pattern: '^[0-9a-fA-F\-]{36}$'
                        tittle:
                            type: string
                        synopsis:
                            type: string
                        original_langueage:
                            type: string
                        runtime:
                            type: string
                        distributor:
                            type: string
                        photo:
                            type: string
                            format: binary
                        trailer:
                            type: string
                            format: binary
                        suitable_for:
                            type: string
                    - oneOf:
                        - $ref: '#/components/schema/Movie'
                        - $ref: '#/components/schema/TvSerie'
                      discriminator:
                          propertyName: categories
                          mapping:
                              Movie: '#/components/schema/Movie'
                              TvSerie: '#/components/schema/TvSerie'
            Movie:
                type: object
                properties:
                    categories:
                        type: string
                    release_theaters_date:
                        type: string
                    release_streaming_date:
                        type: string
                    box_office:
                        type: string
                    at_teather:
                        type: string
                required:
                    - categories
            TvSerie:
                type: object
                properties:
                    categories:
                        type: string
                    release_streaming_date:
                        type: string
                required:
                    - categories
            Episodes:
                type: object
                properties:
                    uuid:
                        type: string
                        pattern: '^[0-9a-fA-F\-]{36}$'
                    belong_tv_serie:
                        type: string
                        pattern: '^[0-9a-fA-F\-]{36}$'
                    episode_season:
                        type: string
                    episode_air_date:
                        type: string
                    episode_synopsis:
                        type: string
                    episode_photo:
                        type: string
                        format: binary
                    episode_runtime:
                        type: string
            Staff:
                type: object
                properties:
                    uuid:
                        type: string
                        pattern: '^[0-9a-fA-F\-]{36}$'
                    staff_first_name:
                        type: string
                    staff_last_name:
                        type: string
                staff_biography:
                    type: string
                staff_birthday:
                    type: string
                staff_profile_photo:
                    type: string
                    format: binary
        Season:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belong_tv_serie:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                season_number:
                    type: string
                season_synopsis:
                    type: string
                season_num_episodes:
                    type: string
                season_release_date:
                    type: string
        Photo:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belong_film:
                    type: array
                    items:
                        $ref: '#/components/schema/Film'
                photo:
                    type: string
                    format: binary
        Video:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belong_film:
                    type: array
                    items:
                        $ref: '#/components/schema/Film'
                video:
                    type: string
                    format: binary
        Rating:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                belong_film:
                    type: array
                    items:
                        $ref: '#/components/schema/Film'
                rate_user:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                rating:
                    type: number
        Genre:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                genre:
                    type: string
        Stream_Sites:
            type: object
            properties:
                uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                stream_site_name:
                    type: string
                stream_site_logo:
                    type: string
                    format: binary
                stream_site_month_price:
                    type: string
paths:
    /users:
        post:
            summary: Register User
            responses:
                '201':
                    description: Created
                    headers:
                        Location:
                            schema:
                                type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
    /users/{uuid}:
        parameters:
            - schema:
                type: string
              name: uuid
              in: path
              required: true
        get:
            summary: View User
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
        put:
            summary: Modify User
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
        delete:
            summary: Delete User
            responses:
                '204':
                    description: No content
    /movies:
        post:
            summary: Create Movie
            responses:
                '201':
                    description: Created
                    headers:
                        Location:
                            schema:
                                type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Movie'
        get:
            summary: List All Movies
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Movie'
    /movies/{uuid}:
        parameters:
            - schema:
                type: string
              name: uuid
              in: path
              required: true
        get:
            summary: View Movie
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
        put:
            summary: Modify Movie
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Movie'
        delete:
            summary: Delete Movie
            responses:
                '204':
                    description: No content
    /staffs:
        post:
            summary: Create Staff 
            responses:
                '201':
                    description: Created
                    headers:
                        Location:
                            schema:
                                type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Staff'
        get:
            summary: List All Staffs
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Staff'
    /staffs/{uuid}:
        parameters:
            - schema:
                type: string
              name: uuid
              in: path
              required: true
        get:
            summary: View Staff
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Staff'
        put:
            summary: Modify Staff
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Staff'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Staff'
        delete:
            summary: Delete Staff
            responses:
                '204':
                    description: No content
    /tv-series:
        post:
            summary: Create TV Serie
            responses:
                '201':
                    description: Created
                    headers:
                        Location:
                            schema:
                                type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Tv_Serie'
        get:
            summary: List All TV Series
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Tv_Serie'
    /tv-serie/{uuid}:
        parameters:
            - schema:
                type: string
              name: uuid
              in: path
              required: true
        get:
            summary: View TV Serie
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tv_Serie'
        put:
            summary: Modify TV Serie
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tv_Serie'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Tv_Serie'
        delete:
            summary: Delete TV Serie
            responses:
                '204':
                    description: No content
