export const menuPanel = {
    movies: {
        0: {
            tittle: 'MOVIES IN THEATHERS',
            id: '0XP4',
            subItems: {
                0: {
                    image: '',
                    text: 'Opening this week',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'XQ07',
                },
                1: {
                    image: '',
                    text: 'Coming soon to theathers',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'VVMD',
                },
                2: {
                    image: '',
                    text: 'Certified movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'WBKU',
                },
            },
        },
        1: {
            tittle: 'MOVIES AT HOME',
            id: 'HTJM',
            subItems: {
                0: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '4WUQ',
                },
                1: {
                    image: '',
                    text: 'Top Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '20GV',
                },
                2: {
                    image: '',
                    text: 'Peacock',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'CGEM',
                },
                3: {
                    image: '',
                    text: 'Vudu',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'OYDE',
                },
                4: {
                    image: '',
                    text: 'Netflix',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'LRO8',
                },
                5: {
                    image: '',
                    text: 'Apple TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'JWAN',
                },
                6: {
                    image: '',
                    text: 'Amazon prime',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'JCY4',
                },
                7: {
                    image: '',
                    text: 'Certified Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '537W',
                },
                8: {
                    image: '',
                    text: 'Most popular Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'SXIR',
                },
                9: {
                    image: '',
                    text: 'Browse all',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'Q146',
                },
            },
        },
        2: {
            tittle: 'MORE',
            id: '0HSN',
            subItems: {
                0: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'CZ1F',
                },
                1: {
                    image: '',
                    text: 'Top Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'Z2BJ',
                },
                2: {
                    image: '',
                    text: 'Trailers',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'X6YO',
                },
            },
        },
        3: {
            tittle: 'CERTIFIED FRESH PICKS',
            id: '7MM5',
            subItems: {
                0: {
                    image: './prey.webp',
                    text: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
                    rating: '40%',
                    ratingImg: 2,
                    textType: 'movieImg',
                    id: 'S4VX',
                },
                1: {
                    image: './prey.webp',
                    text: 'Prey',
                    rating: '81%',
                    ratingImg: 3,
                    textType: 'movieImg',
                    id: 'FY51',
                },
                2: {
                    image: './prey.webp',
                    text: 'Prey',
                    rating: '81%',
                    ratingImg: 3,
                    textType: 'movieImg',
                    id: 'ECR7',
                },
            },
        },
    },
    tv: {
        0: {
            tittle: 'NEW TV TONIGHT',
            id: 'OIFO',
            subItems: {
                0: {
                    image: '',
                    text: 'billions: Season 6',
                    rating: '50%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                    id: 'ZAOG',
                },
                1: {
                    image: '',
                    text: 'The Chosen One: season 0',
                    rating: '--',
                    ratingImg: 4,
                    textType: 'movieRtng',
                    id: 'M3ZK',
                },
                2: {
                    image: '',
                    text: 'The Upshaws: Season 3',
                    rating: '--',
                    ratingImg: 4,
                    textType: 'movieRtng',
                    id: 'L7LP',
                },
                3: {
                    image: '',
                    text: 'Solar Opposites: Season 3',
                    rating: '--',
                    ratingImg: 4,
                    textType: 'movieRtng',
                    id: 'VN9G',
                },
                4: {
                    image: '',
                    text: 'My Dad the Bounty Hunter: Season 4',
                    rating: '38%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                    id: 'GFIY',
                },
            },
        },
        1: {
            tittle: 'MOST POPULAR TV ON RT',
            id: '38T2',
            subItems: {
                0: {
                    image: '',
                    text: 'Painkiller: Season 0',
                    rating: '38%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                    id: '1DFH',
                },
                1: {
                    image: '',
                    text: 'Only murders in the Building: Sea the mother of god',
                    rating: '88%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                    id: 'BT3Y',
                },
                2: {
                    image: '',
                    text: 'Dark Winds: Season 1',
                    rating: '100%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                    id: 'NACQ',
                },
                3: {
                    image: '',
                    text: 'The Crowded Room: Season 0',
                    rating: '22%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                    id: 'ADNK',
                },
                4: {
                    image: '',
                    text: 'Painkiller: Season 0',
                    rating: '38%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                    id: '9IZ0',
                },
                5: {
                    image: '',
                    text: 'Only murders in the Building: Sea the mother of god',
                    rating: '88%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                    id: 'IOXG',
                },
                6: {
                    image: '',
                    text: 'Dark Winds: Season 1',
                    rating: '100%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                    id: 'UGW9',
                },
                7: {
                    image: '',
                    text: 'The Crowded Room: Season 0',
                    rating: '22%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                    id: 'R9HC',
                },
            },
        },
        2: {
            tittle: 'MORE',
            id: 'PETI',
            subItems: {
                0: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'PURZ',
                },
                1: {
                    image: '',
                    text: 'Top TV Shows',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'BLQR',
                },
                2: {
                    image: '',
                    text: 'Peacock',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'YEBV',
                },
                3: {
                    image: '',
                    text: 'Vudu',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'WJN0',
                },
                4: {
                    image: '',
                    text: 'Netflix',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '6ZLH',
                },
                5: {
                    image: '',
                    text: 'Apple TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'IHKA',
                },
                6: {
                    image: '',
                    text: 'Amazon prime',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'EJVD',
                },
                7: {
                    image: '',
                    text: 'Most popular streaming movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'DOHJ',
                },
                8: {
                    image: '',
                    text: 'Certified TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'DUF0',
                },
                9: {
                    image: '',
                    text: 'Most popular TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'YMES',
                },
                10: {
                    image: '',
                    text: 'Browse all',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'LFPW',
                },
            },
        },
        3: {
            tittle: 'CERTIFIED FRESH PICKS',
            id: 'KKBB',
            subItems: {
                0: {
                    image: '/./prey.webp',
                    text: 'Prey',
                    rating: '81%',
                    ratingImg: 2,
                    textType: 'movieImg',
                    id: 'U08S',
                },
            },
        },
    },
    news: {
        0: {
            tittle: 'TOPICS',
            id: '5R8K',
            subItems: {
                0: {
                    image: '',
                    text: 'Comics on TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'TKJE',
                },
                1: {
                    image: '',
                    text: 'All-Time Lists',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'RP5T',
                },
                2: {
                    image: '',
                    text: 'Countdown',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '152A',
                },
                3: {
                    image: '',
                    text: 'Five Favorite Films',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'MN23',
                },
                4: {
                    image: '',
                    text: 'Video Interviews',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '9QCX',
                },
                5: {
                    image: '',
                    text: 'Weekend Box Office',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: '8UZC',
                },
                6: {
                    image: '',
                    text: 'Weekly Ketchup',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'HAWT',
                },
                7: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                    id: 'TSVL',
                },
            },
        },
        1: {
            tittle: 'GUIDES',
            id: 'GL6P',
            subItems: {
                0: {
                    image: './guidesNews.PNG',
                    text: '10 best Jenifer Lawrence Movies Ranked',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                    id: 'FQSU',
                },
                1: {
                    image: './guidesNews.PNG',
                    text: '36 Best Denzel Washintong Movies Ranked',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                    id: 'P6QB',
                },
            },
        },
        2: {
            tittle: 'HUBS',
            id: 'IH99',
            subItems: {
                0: {
                    image: './guidesNews.PNG',
                    text: 'TR14: Celebrating 14 Years of Toren Romaros',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                    id: 'SX6Q',
                },
                1: {
                    image: './guidesNews.PNG',
                    text: 'What to Watch: In Theathers and On Streaming',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                    id: '3P6I',
                },
            },
        },
        3: {
            tittle: 'TR NEWS',
            id: 'QIGC',
            subItems: {
                0: {
                    image: './guidesNews.PNG',
                    text: 'The Most Anticipated TV and Streaming Shows of 911: New And Returning Shows We Can"t Wait to see',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                    id: 'PN2R',
                },
                1: {
                    image: './guidesNews.PNG',
                    text: 'Weekend Box Office Results: Barbie Leads for Fourth Week in a Row',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                    id: 'Z308',
                },
            },
        },
    },
}

export const profilePanel = [
    'User',
    'Config',
    'Favorite',
    'Profile',
    'Followers',
    'Log out',
]
