export const menuPanel = {
    movies: {
        0: {
            tittle: 'MOVIES IN THEATHERS',
            subItems: {
                0: {
                    image: '',
                    text: 'Opening this week',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                1: {
                    image: '',
                    text: 'Coming soon to theathers',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                2: {
                    image: '',
                    text: 'Certified movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
            },
        },
        1: {
            tittle: 'MOVIES AT HOME',
            subItems: {
                0: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                1: {
                    image: '',
                    text: 'Top Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                2: {
                    image: '',
                    text: 'Peacock',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                3: {
                    image: '',
                    text: 'Vudu',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                4: {
                    image: '',
                    text: 'Netflix',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                5: {
                    image: '',
                    text: 'Apple TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                6: {
                    image: '',
                    text: 'Amazon prime',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                7: {
                    image: '',
                    text: 'Certified Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                8: {
                    image: '',
                    text: 'Most popular Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                9: {
                    image: '',
                    text: 'Browse all',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
            },
        },
        2: {
            tittle: 'MORE',
            subItems: {
                0: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                1: {
                    image: '',
                    text: 'Top Movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                2: {
                    image: '',
                    text: 'Trailers',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
            },
        },
        3: {
            tittle: 'CERTIFIED FRESH PICKS',
            subItems: {
                0: {
                    image: './prey.webp',
                    text: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
                    rating: '40%',
                    ratingImg: 2,
                    textType: 'movieImg',
                },
                1: {
                    image: './prey.webp',
                    text: 'Prey',
                    rating: '81%',
                    ratingImg: 3,
                    textType: 'movieImg',
                },
                2: {
                    image: './prey.webp',
                    text: 'Prey',
                    rating: '81%',
                    ratingImg: 3,
                    textType: 'movieImg',
                },
            },
        },
    },
    tv: {
        0: {
            tittle: 'NEW TV TONIGHT',
            subItems: {
                0: {
                    image: '',
                    text: 'billions: Season 6',
                    rating: '50%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                },
                1: {
                    image: '',
                    text: 'The Chosen One: season 0',
                    rating:'--',
                    ratingImg: 4,
                    textType: 'movieRtng',
                },
                2: {
                    image: '',
                    text: 'The Upshaws: Season 3',
                    rating:'--',
                    ratingImg: 4,
                    textType: 'movieRtng',
                },
                3: {
                    image: '',
                    text: 'Solar Opposites: Season 3',
                    rating:'--',
                    ratingImg: 4,
                    textType: 'movieRtng',
                },
                4: {
                    image: '',
                    text: 'My Dad the Bounty Hunter: Season 4',
                    rating: '38%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                },
            },
        },
        1: {
            tittle: 'MOST POPULAR TV ON RT',
            subItems: {
                0: {
                    image: '',
                    text: 'Painkiller: Season 0',
                    rating: '38%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                },
                1: {
                    image: '',
                    text: 'Only murders in the Building: Sea the mother of god',
                    rating: '88%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                },
                2: {
                    image: '',
                    text: 'Dark Winds: Season 1',
                    rating: '100%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                },
                3: {
                    image: '',
                    text: 'The Crowded Room: Season 0',
                    rating: '22%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                },
                4: {
                    image: '',
                    text: 'Painkiller: Season 0',
                    rating: '38%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                },
                5: {
                    image: '',
                    text: 'Only murders in the Building: Sea the mother of god',
                    rating: '88%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                },
                6: {
                    image: '',
                    text: 'Dark Winds: Season 1',
                    rating: '100%',
                    ratingImg: 2,
                    textType: 'movieRtng',
                },
                7: {
                    image: '',
                    text: 'The Crowded Room: Season 0',
                    rating: '22%',
                    ratingImg: 1,
                    textType: 'movieRtng',
                },
            },
        },
        2: {
            tittle: 'MORE',
            subItems: {
                0: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                1: {
                    image: '',
                    text: 'Top TV Shows',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                2: {
                    image: '',
                    text: 'Peacock',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                3: {
                    image: '',
                    text: 'Vudu',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                4: {
                    image: '',
                    text: 'Netflix',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                5: {
                    image: '',
                    text: 'Apple TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                6: {
                    image: '',
                    text: 'Amazon prime',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                7: {
                    image: '',
                    text: 'Most popular streaming movies',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                8: {
                    image: '',
                    text: 'Certified TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                9: {
                    image: '',
                    text: 'Most popular TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                10: {
                    image: '',
                    text: 'Browse all',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
            },
        },
        3: {
            tittle: 'CERTIFIED FRESH PICKS',
            subItems: {
                0: {
                    image: './prey.webp',
                    text: 'Prey',
                    rating: '81%',
                    ratingImg: 2,
                    textType: 'movieImg',
                },
            },
        },
    },
    news: {
        0: {
            tittle: 'TOPICS',
            subItems: {
                0: {
                    image: '',
                    text: 'Comics on TV',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                1: {
                    image: '',
                    text: 'All-Time Lists',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                2: {
                    image: '',
                    text: 'Countdown',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                3: {
                    image: '',
                    text: 'Five Favorite Films',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                4: {
                    image: '',
                    text: 'Video Interviews',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                5: {
                    image: '',
                    text: 'Weekend Box Office',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                6: {
                    image: '',
                    text: 'Weekly Ketchup',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
                7: {
                    image: '',
                    text: 'What to Watch',
                    rating: '',
                    ratingImg: '',
                    textType: 'default',
                },
            },
        },
        1: {
            tittle: 'GUIDES',
            subItems: {
                0: {
                    image: './guidesNews.PNG',
                    text: '10 best Jenifer Lawrence Movies Ranked',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                },
                1: {
                    image: './guidesNews.PNG',
                    text: '36 Best Denzel Washintong Movies Ranked',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                },
            },
        },
        2: {
            tittle: 'HUBS',
            subItems: {
                0: {
                    image: './guidesNews.PNG',
                    text: 'TR14: Celebrating 14 Years of Toren Romaros',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                },
                1: {
                    image: './guidesNews.PNG',
                    text: 'What to Watch: In Theathers and On Streaming',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                },
            },
        },
        3: {
            tittle: 'TR NEWS',
            subItems: {
                0: {
                    image: './guidesNews.PNG',
                    text: 'The Most Anticipated TV and Streaming Shows of 911: New And Returning Shows We Can"t Wait to see',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                },
                1: {
                    image: './guidesNews.PNG',
                    text: 'Weekend Box Office Results: Barbie Leads for Fourth Week in a Row',
                    rating: '',
                    ratingImg: '',
                    textType: 'news',
                },
            },
        },
    },
}
